name: BattleScheduler

main: com.alk.battleScheduler.BattleScheduler
version: 1.2.6
depend: []

author: Alkarin
description: Scheduling System for Battlecraft
commands:
  timer:
    aliases:
    description: Control Events
    usage: |
        /timer list :&f see all timers and registered events
        /timer create <time> <event>:&f Create a timer
              Example:&f timer create * * * * * BattleChestEvent
        /timer delete <number>:&f Delete a timer
        /timer execute <event>:&f Execute the given event
